import { PracticeTask } from './types';

// Biology Practice Set
export const BIOLOGY_PRACTICE_TASKS: PracticeTask[] = [
  {
    id: 'bio-1',
    conceptIndex: 1,
    conceptTitle: 'Light-Dependent Reactions & Photophosphorylation',
    topic: 'Biology',
    chapter: 'Chapter 6: Life Processes',
    taskType: 'sequence',
    typeBadge: 'Pathway Ordering',
    title: 'Trace the Photon & Electron Pathway',
    instruction:
      'Arrange the 5 molecular events of non-cyclic photophosphorylation in their precise chronological sequence, from initial solar capture to chemical energy synthesis.',
    contextPill: 'Thylakoid Membrane Machinery',
    estimatedTime: '3 min',
    hint: 'Remember that water is split at Photosystem II (P680) right after excitation to supply replacement electrons, before the electron transport chain pumps protons.',
    whyExplanation: {
      coreInsight:
        'Electrons flow in a strictly unidirectional "Z-scheme" pathway: PS II ➔ Photolysis ➔ ETC (Cytochrome b₆f) ➔ PS I ➔ NADPH, with ATP generated by the resulting H⁺ gradient.',
      connectionToLearn:
        'In the Learn diagram, you saw how photon absorption at PS II acts as the spark, while photolysis provides the steady fuel (electrons) that drives proton pumps.',
      scientificMechanism:
        'Non-cyclic electron flow generates both ATP and NADPH in roughly equal amounts, which are immediately exported to the stroma for the Calvin Cycle.',
    },
    sequenceData: {
      startLabel: 'Sunlight Hits Leaf',
      endLabel: 'Chemical Energy Ready (ATP + NADPH)',
      items: [
        {
          id: 'seq-1',
          label: 'Photon Absorption at Photosystem II (P680)',
          detail: 'Sunlight strikes the antenna pigment complex, boosting reaction center electrons to an excited state.',
          correctOrder: 1,
        },
        {
          id: 'seq-2',
          label: 'Photolysis: Splitting of Water (H₂O)',
          detail: 'The oxygen-evolving complex splits 2H₂O into 4H⁺, 4e⁻, and O₂ gas to replace lost electrons in PS II.',
          correctOrder: 2,
        },
        {
          id: 'seq-3',
          label: 'Electron Transport & Proton Pumping',
          detail: 'Electrons pass through Plastoquinone and Cytochrome b₆f, actively pumping H⁺ into the thylakoid lumen.',
          correctOrder: 3,
        },
        {
          id: 'seq-4',
          label: 'PS I Re-excitation & NADPH Formation',
          detail: 'Electrons receive a second photon boost at P700; NADP⁺ reductase transfers electrons to create NADPH.',
          correctOrder: 4,
        },
        {
          id: 'seq-5',
          label: 'Chemiosmosis via ATP Synthase',
          detail: 'Protons stream down their concentration gradient back into the stroma, driving rotary synthesis of ATP.',
          correctOrder: 5,
        },
      ],
    },
  },
  {
    id: 'bio-2',
    conceptIndex: 2,
    conceptTitle: 'Calvin Cycle: Carbon Fixation & Glucose Synthesis',
    topic: 'Biology',
    chapter: 'Chapter 6: Life Processes',
    taskType: 'visual-hotspot',
    typeBadge: 'Interactive Pathway Mapping',
    title: 'Map the Stroma Assembly Line',
    instruction:
      'Assign the correct chemical substrates, energy carriers, and products to each stage of the Calvin Cycle to complete the glucose synthesis pathway.',
    contextPill: 'Chloroplast Stroma Reaction',
    estimatedTime: '4 min',
    hint: 'RuBisCO fixes 1-carbon CO₂ onto 5-carbon RuBP. Reduction requires the ATP and NADPH created during light reactions, yielding net G3P sugar.',
    whyExplanation: {
      coreInsight:
        'The Calvin cycle operates in three sequential phases: Carbon Fixation (catalyzed by RuBisCO), Reduction (fueled by ATP & NADPH), and RuBP Regeneration (fueled by ATP).',
      connectionToLearn:
        'Recall from the Learn model that 3 turns of the cycle consume 9 ATP and 6 NADPH to export one 3-carbon G3P molecule, which later forms glucose.',
      scientificMechanism:
        'Without the ATP and NADPH produced in the thylakoid membranes, the reduction phase halts, stalling the entire carbon fixation cycle.',
    },
    hotspotData: {
      diagramTitle: 'Calvin Cycle Stage Assembly',
      diagramSubtitle: 'Match each chemical compound or carrier to its active role in the cycle.',
      targets: [
        {
          id: 'target-1',
          stageName: 'Stage 1: Fixation Input',
          slotLabel: 'Inorganic Carbon Gas Input',
          correctTokenId: 'token-co2',
          hint: 'The 1-carbon atmospheric gas captured by RuBisCO.',
        },
        {
          id: 'target-2',
          stageName: 'Stage 2: Reduction Fuel',
          slotLabel: 'Light-Reaction Chemical Batteries',
          correctTokenId: 'token-atp-nadph',
          hint: 'High-energy molecules transferred from the thylakoid.',
        },
        {
          id: 'target-3',
          stageName: 'Stage 3: Net Exported Sugar',
          slotLabel: '3-Carbon Sugar Output (G3P)',
          correctTokenId: 'token-g3p',
          hint: 'The actual exported building block of glucose and starch.',
        },
        {
          id: 'target-4',
          stageName: 'Stage 4: Acceptor Regeneration',
          slotLabel: '5-Carbon Carbon Dioxide Acceptor',
          correctTokenId: 'token-rubp',
          hint: 'The recycled molecule that combines with incoming CO₂.',
        },
      ],
      tokens: [
        {
          id: 'token-co2',
          label: 'Carbon Dioxide',
          formula: 'CO₂ (1C)',
          category: 'input',
        },
        {
          id: 'token-atp-nadph',
          label: 'ATP + NADPH',
          formula: '9 ATP + 6 NADPH',
          category: 'intermediate',
        },
        {
          id: 'token-g3p',
          label: 'Glyceraldehyde-3-phosphate',
          formula: 'G3P (3C Triose)',
          category: 'product',
        },
        {
          id: 'token-rubp',
          label: 'Ribulose-1,5-bisphosphate',
          formula: 'RuBP (5C)',
          category: 'acceptor',
        },
      ],
    },
  },
  {
    id: 'bio-3',
    conceptIndex: 3,
    conceptTitle: 'Cellular Respiration & Glycolytic Pathway',
    topic: 'Biology',
    chapter: 'Chapter 6: Life Processes',
    taskType: 'scenario',
    typeBadge: 'Clinical & Lab Scenario',
    title: 'Analyze Metabolic Pathway Blockage',
    instruction:
      'Read the experimental laboratory scenario below and determine the exact biochemical consequence on cellular energy yield.',
    contextPill: 'Cytoplasmic Respiration',
    estimatedTime: '3 min',
    hint: 'Focus on where Phosphofructokinase-1 acts in the glycolytic pathway: it catalyzes the irreversible investment of the second ATP before glucose is cleaved.',
    whyExplanation: {
      coreInsight:
        'Phosphofructokinase-1 (PFK-1) is the primary rate-limiting and committed step of glycolysis. Inhibiting PFK-1 prevents the formation of Fructose-1,6-bisphosphate.',
      connectionToLearn:
        'As explored in the Learn module, if the energy investment phase is interrupted, the cell cannot proceed to cleavage or the 4 ATP payoff phase.',
      scientificMechanism:
        'Because no downstream G3P is generated, pyruvate production drops to zero, depriving mitochondria of fuel for the Krebs cycle.',
    },
    scenarioData: {
      story:
        'In a cellular biochemistry laboratory, researchers treat human muscle cells with a synthetic inhibitor that selectively binds and inactivates Phosphofructokinase-1 (PFK-1), the third enzyme of glycolysis.',
      question:
        'What immediate metabolic impact will be observed in these treated cells when supplied with glucose in the presence of oxygen?',
      options: [
        {
          id: 'opt-a',
          letter: 'A',
          title: 'Immediate drop in cytosolic pyruvate & shutdown of ATP payoff',
          description:
            'Glucose cannot be converted past Fructose-6-phosphate; downstream cleavage and the +4 ATP payoff phase fail to occur.',
          isCorrect: true,
          feedback:
            'Spot on! PFK-1 is the key committed step. Blocking it halts the pathway before cleavage, preventing any pyruvate, NADH, or payoff ATP production.',
        },
        {
          id: 'opt-b',
          letter: 'B',
          title: 'Doubling of lactic acid fermentation yield',
          description:
            'The cell compensates by rapidly converting glucose directly into lactate without requiring enzymes.',
          isCorrect: false,
          feedback:
            'Lactic acid fermentation requires pyruvate as its substrate. Without PFK-1 activity, no pyruvate is made, so fermentation cannot occur.',
        },
        {
          id: 'opt-c',
          letter: 'C',
          title: 'Direct consumption of glucose by mitochondrial cristae',
          description:
            'Mitochondria absorb raw 6-carbon glucose directly across their inner membranes to bypass the cytosol.',
          isCorrect: false,
          feedback:
            'Mitochondria cannot import or utilize raw glucose directly; they require pyruvate transported from cytoplasmic glycolysis.',
        },
        {
          id: 'opt-d',
          letter: 'D',
          title: 'Net gain of 2 ATP with normal pyruvate accumulation',
          description:
            'The remaining enzymes bypass PFK-1 and complete the standard energy balance.',
          isCorrect: false,
          feedback:
            'PFK-1 is an obligatory, non-bypassable enzyme in the classic glycolytic pathway.',
        },
      ],
    },
  },
  {
    id: 'bio-4',
    conceptIndex: 4,
    conceptTitle: 'Oxidative Phosphorylation & ATP Yields',
    topic: 'Biology',
    chapter: 'Chapter 6: Life Processes',
    taskType: 'matching',
    typeBadge: 'Mitochondrial Component Matching',
    title: 'Match Electron Transport Chain Machinery',
    instruction:
      'Connect each mitochondrial structure, electron donor, or enzyme to its precise function in oxidative phosphorylation.',
    contextPill: 'Mitochondrial Cristae & Matrix',
    estimatedTime: '4 min',
    hint: 'NADH enters at Complex I (pumping more protons), FADH₂ at Complex II, Oxygen receives final electrons, and ATP Synthase harnesses the resulting gradient.',
    whyExplanation: {
      coreInsight:
        'Oxidative phosphorylation couples the exergonic flow of electrons down a redox gradient to the endergonic synthesis of ATP via a proton motive force.',
      connectionToLearn:
        'In the Learn visual, you saw the rotary mechanism of the F₀F₁ ATP Synthase turbine spinning as protons rush back into the mitochondrial matrix.',
    },
    matchingData: {
      leftTitle: 'Component / Carrier',
      rightTitle: 'Biochemical Role in ATP Synthesis',
      pairs: [
        {
          id: 'match-1',
          source: 'NADH (from Krebs & Glycolysis)',
          target: 'Donates electrons at Complex I; yields ~2.5 ATP via proton pumping.',
          hint: 'The primary high-energy electron carrier produced during carbohydrate breakdown.',
        },
        {
          id: 'match-2',
          source: 'Molecular Oxygen (O₂)',
          target: 'Terminal electron acceptor at Complex IV, forming metabolic H₂O.',
          hint: 'The vital molecule consumed during aerobic respiration.',
        },
        {
          id: 'match-3',
          source: 'Intermembrane Space',
          target: 'Reservoir where H⁺ protons accumulate to build high electrochemical potential.',
          hint: 'The narrow compartment between the outer and inner mitochondrial membranes.',
        },
        {
          id: 'match-4',
          source: 'F₀F₁ ATP Synthase Rotor',
          target: 'Molecular turbine that synthesizes ATP as protons stream back into matrix.',
          hint: 'The catalytic dynamo that produces ~28 ATP per glucose.',
        },
      ],
    },
  },
];

// Mathematics Practice Set
export const MATH_PRACTICE_TASKS: PracticeTask[] = [
  {
    id: 'math-1',
    conceptIndex: 1,
    conceptTitle: 'Differential Calculus & Chain Rule',
    topic: 'Mathematics',
    chapter: 'Calculus I: Derivatives',
    taskType: 'numeric',
    typeBadge: 'Formula Calculation',
    title: 'Evaluate Derivative at Point x = 2',
    instruction:
      'Given f(x) = (3x² - 4)³, compute the numerical value of the first derivative f\'(2).',
    contextPill: 'Chain Rule Application',
    estimatedTime: '2 min',
    hint: 'Let u = 3x² - 4. Then f(x) = u³. Apply Chain Rule: f\'(x) = 3u² · u\'. Note u(2) = 8 and u\'(2) = 12.',
    whyExplanation: {
      coreInsight:
        'The Chain Rule states d/dx[g(h(x))] = g\'(h(x)) · h\'(x). For (3x² - 4)³, the inner derivative is 6x. At x = 2, f\'(2) = 3(8)² · (12) = 2304.',
      connectionToLearn:
        'Recall from the rates of change module that composite functions require scaling the outer rate of change by the inner rate of change.',
    },
    numericData: {
      problemStatement: 'Calculate f\'(2) for f(x) = (3x² - 4)³',
      unit: '',
      correctValue: 2304,
      tolerance: 0,
      formulaHint: 'f\'(x) = 3(3x² - 4)² · 6x',
    },
  },
  {
    id: 'math-2',
    conceptIndex: 2,
    conceptTitle: 'Optimization & Critical Points',
    topic: 'Mathematics',
    chapter: 'Calculus I: Applications',
    taskType: 'short-answer',
    typeBadge: 'Mathematical Explanation',
    title: 'Explain the Second Derivative Test',
    instruction:
      'Briefly state how the sign of f\'\'(c) determines whether a critical point c (where f\'(c) = 0) is a local minimum or maximum.',
    contextPill: 'Concavity & Extreme Values',
    estimatedTime: '3 min',
    hint: 'Think about concavity: positive second derivative means concave upward (like a cup), while negative means concave downward.',
    whyExplanation: {
      coreInsight:
        'If f\'\'(c) > 0, the function is concave upward at c, so the horizontal tangent at c is a local minimum. If f\'\'(c) < 0, it is concave downward (local maximum).',
      connectionToLearn:
        'Visualizing the curvature helps establish why positive concavity forces tangent slopes to increase from negative to positive across c.',
    },
    shortAnswerData: {
      prompt: 'Describe the outcome when f\'\'(c) > 0 vs f\'\'(c) < 0:',
      placeholder: 'e.g., When f\'\'(c) > 0 the critical point is a local minimum because the curve is concave up...',
      acceptableAnswers: ['minimum', 'local min', 'concave up'],
      sampleAnswer:
        'When f\'\'(c) > 0, the function is concave upward, making c a local minimum. When f\'\'(c) < 0, the function is concave downward, making c a local maximum.',
    },
  },
];

// Computer Science / Programming Practice Set
export const CODE_PRACTICE_TASKS: PracticeTask[] = [
  {
    id: 'code-1',
    conceptIndex: 1,
    conceptTitle: 'Algorithms & Recursion',
    topic: 'Computer Science',
    chapter: 'Data Structures & Algorithms',
    taskType: 'code',
    typeBadge: 'Code Completion',
    title: 'Complete the Base Case for Recursive Binary Search',
    instruction:
      'Modify the recursive binary search implementation so it correctly returns -1 when the low index exceeds the high index.',
    contextPill: 'Logarithmic Search Algorithm',
    estimatedTime: '3 min',
    hint: 'The search range is empty when low > high. Return -1 to signify target not found.',
    whyExplanation: {
      coreInsight:
        'Without a proper base condition when low > high, recursive search calls will result in infinite recursion and stack overflow errors.',
      connectionToLearn:
        'In the array search visualization, the pointer bounds low and high cross each other when the element is absent.',
    },
    codeData: {
      language: 'JavaScript',
      initialCode: `function binarySearch(arr, target, low, high) {\n  // FIXME: Add base condition here\n  if (low > high) return -1;\n\n  const mid = Math.floor((low + high) / 2);\n  if (arr[mid] === target) return mid;\n  if (arr[mid] > target) return binarySearch(arr, target, low, mid - 1);\n  return binarySearch(arr, target, mid + 1, high);\n}`,
      goal: 'Return -1 when low > high',
      expectedOutputOrToken: 'if (low > high) return -1',
      solutionSnippet: 'if (low > high) return -1;',
    },
  },
  {
    id: 'code-2',
    conceptIndex: 2,
    conceptTitle: 'Time Complexity & Big O Analysis',
    topic: 'Computer Science',
    chapter: 'Algorithm Design',
    taskType: 'multiple-choice',
    typeBadge: 'Complexity Analysis',
    title: 'Identify the Time Complexity of Nested Loops',
    instruction:
      'Determine the worst-case asymptotic time complexity of an algorithm that performs an outer loop n times and an inner loop i times.',
    contextPill: 'Asymptotic Bounds',
    estimatedTime: '2 min',
    hint: 'Summing 1 + 2 + 3 + ... + n yields n(n+1)/2 operations.',
    whyExplanation: {
      coreInsight:
        'The total iterations equal n(n+1)/2 = 0.5n² + 0.5n. Dropping lower-order terms and coefficients yields O(n²).',
      connectionToLearn:
        'In the algorithmic efficiency chapter, triangular sums represent quadratic growth patterns.',
    },
    multipleChoiceData: {
      question: 'What is the Big O time complexity for summing i from 1 to n in nested loops?',
      options: [
        {
          id: 'mc-1',
          label: 'A',
          text: 'O(n²)',
          isCorrect: true,
          explanation: 'Correct! The sum of the first n integers is n(n+1)/2, which is O(n²).',
        },
        {
          id: 'mc-2',
          label: 'B',
          text: 'O(n log n)',
          isCorrect: false,
          explanation: 'O(n log n) is typical for divide-and-conquer sorting (Merge Sort), not triangular loop iteration.',
        },
        {
          id: 'mc-3',
          label: 'C',
          text: 'O(n)',
          isCorrect: false,
          explanation: 'Linear time would require the inner loop to run a constant number of times independent of i.',
        },
      ],
    },
  },
];

// Main export array for default compatibility
export const PRACTICE_TASKS: PracticeTask[] = BIOLOGY_PRACTICE_TASKS;

// Dynamic practice generator based on uploaded context/source
export function getPracticeTasksForSource(sourceName?: string, conceptTitle?: string): PracticeTask[] {
  const query = `${sourceName || ''} ${conceptTitle || ''}`.toLowerCase();

  if (query.includes('math') || query.includes('calculus') || query.includes('derivative') || query.includes('algebra')) {
    return MATH_PRACTICE_TASKS;
  }

  if (query.includes('code') || query.includes('algorithm') || query.includes('computer') || query.includes('python') || query.includes('java')) {
    return CODE_PRACTICE_TASKS;
  }

  return BIOLOGY_PRACTICE_TASKS;
}
